---
  - name: Debug | scope of work
    debug: msg="installing '{{ mongo_family }}' family version '{{ mongo_version }}'"

  - name: Mongo | Check mongo_version variable
    assert:
      that: str(mongo_version) in [ "2.6", "3", "3.2", "3.4", "3.6", "4.0", "4.2" ]
    tags:
       -mongo

  - name: Mongo | Check mongo_family variable
    assert:
      that: mongo_family in [ "org", "enterprise" ]
    tags:
       -mongo

  - name: Mongo | set repo suffix fact
    set_fact:
      mongo_repo_suffix: com
    when: mongo_family=="enterprise"

  - include_tasks: __detect_init_system.yml

  - name: Include release related vars
    include_vars: "{{ item }}"
    with_first_found:
     - "{{ role_dir }}/defaults/{{ ansible_distribution_release }}_vars.yml"
     - "{{ role_dir }}/defaults/default_vars.yml"

  - name: Debug |
    debug: msg="About to install {{ mongo_version }}"

  - include_tasks: tasks_mongodb_2.6.yml
    when: mongo_version == "2.6"

  - include_tasks: tasks_mongodb_3.yml
    when: mongo_version == "3"

  - include_tasks: tasks_mongodb_32.yml
    when: mongo_version == "3.2"

  - include_tasks: tasks_mongodb_34.yml
    when: mongo_version == "3.4"

  - include_tasks: tasks_mongodb_36.yml
    when: mongo_version == "3.6"

  - include_tasks: tasks_mongodb_40.yml
    when: mongo_version == "4.0"

  - include_tasks: tasks_mongodb_42.yml
    when: mongo_version == "4.2"

  - include_tasks: mongo_cfg_patch.yml
