---
  # Parameters:
  #  prudentia_dir (provided)

  - name: MongoDB | set service name fact
    set_fact:
      mongodb_service_name: mongod

  - name: MongoDB 36 | Check if is present
    command: test -x /usr/bin/mongo
    when: ansible_system == "Linux"
    ignore_errors: yes
    register: mongo_present
    tags: mongodb3

  - name: MongoDB 36 | Add GPG key to apt keyring
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.6.asc
      state: present
    become: yes
    tags: mongodb3

  - name: Debug | deb line
    debug: msg="deb {{ apt_source.arch }} https://repo.mongodb.{{ mongo_repo_suffix }}/apt/ubuntu {{ apt_source.mongodb }}/mongodb-{{ mongo_family }}/3.6 multiverse"

  - name: MongoDB 36 | Add Debian apt repository
    apt_repository:
      repo: "deb {{ apt_source.arch }} https://repo.mongodb.{{ mongo_repo_suffix }}/apt/ubuntu {{ apt_source.mongodb }}/mongodb-{{ mongo_family }}/3.6 multiverse"
      state: present
      filename: mongodb
    when: ansible_os_family == "Debian" and mongo_present is failed
    tags: mongodb3
    become: yes

  - name: MongoDB 36 | Install mongodb-{{ mongo_family }}
    apt: update-cache=yes force=yes state=present pkg=mongodb-{{ mongo_family }}
    when: ansible_os_family == "Debian" and mongo_present is failed
    become: yes
    tags: mongodb3

  - name: MongoDB 36 | Ensure data folder exists
    file:
      path: /data/db
      state: directory
      owner: mongodb
      group: mongodb
      mode: "u=rwx,g=r,o="
    become: yes
    tags: mongodb3

  - name: Debug | detected upstart
    debug: var="upstart_system"

  - name: MongoDB 36 | template systemd service
    template:
       src: "{{ role_dir }}/templates/systemd/mongod.service.j2"
       dest: "/etc/systemd/system/mongod.service"
       owner: root
       group: root
       mode: "u=rw,g=r,o=r"
    become: yes
    when: upstart_system == "systemd"

  - name: MongoDB 36 | start service
    service: name=mongod state=started enabled=yes
    become: yes
    when: upstart_system == "systemd" and docker_test is not defined
    tags: mongodb3
