---
- name: Converge
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: auto

  pre_tasks:
    - debug: var="role_under_test"
    - debug: var="ansible_os_family"

    - name: Update packages
      apt: update_cache=yes
      when: ansible_pkg_mgr=="apt"

    - name: Update packages
      dnf: update_cache=yes
      when: ansible_pkg_mgr=="dnf"

    - name: Update packages
      yum: update_cache=yes
      when: ansible_pkg_mgr=="yum"

    - name: Update and upgrade apt packages
      apt:
        upgrade: no
        update_cache: yes
        cache_valid_time: 86400 #One day
      when: ansible_os_family == "Debian"

    - name: Install optional default ubuntu packages sometimes missing on naked debians
      apt:
        name:
          - apt-transport-https
          - openssl
          - gpg
          - libcurl3
        state: present
        update_cache: yes
      become: yes
      ignore_errors: yes
      register: mongo_optional_deps
      when: ansible_os_family == "Debian"


#  roles:
#    - {
#        role: "{{ role_under_test | default('role_under_test') }}",
#        firewall_used: docker,
#        docker_test: true,
#        preferred_python_version: "3"
#      }
  tasks:
   - debug: msg="org - {{molecule_mongo_version}}"

   - name: Apply role runtime
     include_role:
       name: "{{ role_under_test | default('role_under_test') }}"
     vars:
       firewall_used: docker,
       docker_test: true,
       preferred_python_version: "3"
       mongo_version: "{{ molecule_mongo_version | string }}"
